// flow-typed signature: 52099f2abbd68e476e62a70d34be6953
// flow-typed version: <<STUB>>/c-3po_v^0.5.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'c-3po'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'c-3po' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'c-3po/dist/c-3po-rollup' {
  declare module.exports: any;
}

declare module 'c-3po/dist/c3po' {
  declare module.exports: any;
}

declare module 'c-3po/dist/c3po.min' {
  declare module.exports: any;
}

declare module 'c-3po/dist/index' {
  declare module.exports: any;
}

declare module 'c-3po/dist/loader' {
  declare module.exports: any;
}

declare module 'c-3po/dist/mock' {
  declare module.exports: any;
}

declare module 'c-3po/dist/utils' {
  declare module.exports: any;
}

declare module 'c-3po/loader' {
  declare module.exports: any;
}

declare module 'c-3po/src/index' {
  declare module.exports: any;
}

declare module 'c-3po/src/loader' {
  declare module.exports: any;
}

declare module 'c-3po/src/mock' {
  declare module.exports: any;
}

declare module 'c-3po/src/utils' {
  declare module.exports: any;
}

declare module 'c-3po/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'c-3po/dist/c-3po-rollup.js' {
  declare module.exports: $Exports<'c-3po/dist/c-3po-rollup'>;
}
declare module 'c-3po/dist/c3po.js' {
  declare module.exports: $Exports<'c-3po/dist/c3po'>;
}
declare module 'c-3po/dist/c3po.min.js' {
  declare module.exports: $Exports<'c-3po/dist/c3po.min'>;
}
declare module 'c-3po/dist/index.js' {
  declare module.exports: $Exports<'c-3po/dist/index'>;
}
declare module 'c-3po/dist/loader.js' {
  declare module.exports: $Exports<'c-3po/dist/loader'>;
}
declare module 'c-3po/dist/mock.js' {
  declare module.exports: $Exports<'c-3po/dist/mock'>;
}
declare module 'c-3po/dist/utils.js' {
  declare module.exports: $Exports<'c-3po/dist/utils'>;
}
declare module 'c-3po/loader.js' {
  declare module.exports: $Exports<'c-3po/loader'>;
}
declare module 'c-3po/src/index.js' {
  declare module.exports: $Exports<'c-3po/src/index'>;
}
declare module 'c-3po/src/loader.js' {
  declare module.exports: $Exports<'c-3po/src/loader'>;
}
declare module 'c-3po/src/mock.js' {
  declare module.exports: $Exports<'c-3po/src/mock'>;
}
declare module 'c-3po/src/utils.js' {
  declare module.exports: $Exports<'c-3po/src/utils'>;
}
declare module 'c-3po/webpack.config.js' {
  declare module.exports: $Exports<'c-3po/webpack.config'>;
}
