// flow-typed signature: 077f61c2cf5fdb773ea6cefc3d60ee0c
// flow-typed version: <<STUB>>/po-gettext-loader_v^0.1.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'po-gettext-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'po-gettext-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'po-gettext-loader/index' {
  declare module.exports: $Exports<'po-gettext-loader'>;
}
declare module 'po-gettext-loader/index.js' {
  declare module.exports: $Exports<'po-gettext-loader'>;
}
