// flow-typed signature: 139c7498e22890d8b4e68542ed0b5dec
// flow-typed version: <<STUB>>/zenscroll_v^4.0.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'zenscroll'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'zenscroll' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'zenscroll/zenscroll-min' {
  declare module.exports: any;
}

declare module 'zenscroll/zenscroll' {
  declare module.exports: any;
}

// Filename aliases
declare module 'zenscroll/zenscroll-min.js' {
  declare module.exports: $Exports<'zenscroll/zenscroll-min'>;
}
declare module 'zenscroll/zenscroll.js' {
  declare module.exports: $Exports<'zenscroll/zenscroll'>;
}
